version: '3'
services:
  wator-nginx:
    build: nginx-wator
    network_mode: "host"
    volumes:
      - /watorvapor/app_www/services/nginx-wator/sites-available:/etc/nginx/sites-available
      - /etc/certs/www.wator.xyz:/etc/certs/www.wator.xyz
      - /watorvapor/app_www/www_root:/www_root
      - /watorvapor/autogen:/autogen
    command: nginx
    restart: always
  wator-laravel:
    build: laravel-wator
    network_mode: "host"
    volumes:
      - /watorvapor/app_www/wator:/opt/laravel
      - /watorvapor/rsaauth/wator:/opt/rsaauth
      - /watorvapor/wai.storage/conf:/nativeapi
      - /watorvapor/autogen:/autogen
      - /watorvapor/autogen:/autogen
    working_dir: "/opt/laravel"
    command: php artisan serve -vvv --host=127.0.0.1 --port=18080
    restart: always
  wator-laravel-shadow:
    build: laravel-wator
    network_mode: "host"
    volumes:
      - /watorvapor/app_www/wator:/opt/laravel
      - /watorvapor/rsaauth/wator:/opt/rsaauth
      - /watorvapor/wai.storage/conf:/nativeapi
      - /watorvapor/autogen:/autogen
      - /watorvapor/autogen:/autogen
    working_dir: "/opt/laravel"
    command: php artisan serve -vvv --host=127.0.0.1 --port=18081
  wator-laravel-ghost:
    build: laravel-wator
    network_mode: "host"
    volumes:
      - /watorvapor/app_www/wator:/opt/laravel
      - /watorvapor/rsaauth/wator:/opt/rsaauth
      - /watorvapor/wai.storage/conf:/nativeapi
      - /watorvapor/autogen:/autogen
      - /watorvapor/autogen:/autogen
    working_dir: "/opt/laravel"
    command: php artisan serve -vvv --host=127.0.0.1 --port=18082
    restart: always
