version: '3'
services:
  wator-nginx:
    build: nginx-wator
    ports:
      - "18443:443"
    volumes:
      - /watorvapor/app_www/services/nginx-wator/sites-available:/etc/nginx/sites-available
      - /etc/certs/www.wator.xyz:/etc/certs/www.wator.xyz
    command: nginx -T
    #restart: always
  wator-laravel:
    build: laravel-wator
    ports:
      - "127.0.0.1:18080:8000"
    volumes:
      - /watorvapor/app_www/wator:/opt/laravel
    working_dir: "/opt/laravel"
    #command: pwd
    command: php artisan serve --host=0.0.0.0
    restart: always
