version: '3'
services:
  wator-nginx:
    build: nginx-wator
    network_mode: "host"
    volumes:
      - /watorvapor/app_www/services/nginx-wator/sites-available:/etc/nginx/sites-available
      - /watorvapor/app_www/services/nginx-wator/tcp.conf.d:/etc/nginx/tcp.conf.d
      - /watorvapor/cert:/etc/cert
      - /watorvapor/app_www/www_root:/www_root
      - /watorvapor/autogen:/autogen
      - /watorvapor/log/nginx:/log
    command: nginx
    restart: always
  
  wator-laravel:
    build: laravel-wator
    network_mode: "host"
    volumes:
      - /watorvapor/app_www/wator:/opt/laravel
      - /watorvapor/rsaauth/wator:/opt/rsaauth
      - /watorvapor/wai.storage/conf:/nativeapi
      - /watorvapor/autogen:/autogen
      - /watorvapor/story.storage/repository.wator:/repository
    working_dir: "/opt/laravel"
    command: php artisan serve -vvv --host=127.0.0.1 --port=18080
    restart: always
  
  wator-laravel-shadow:
    build: laravel-wator
    network_mode: "host"
    volumes:
      - /watorvapor/app_www/wator:/opt/laravel
      - /watorvapor/rsaauth/wator:/opt/rsaauth
      - /watorvapor/wai.storage/conf:/nativeapi
      - /watorvapor/autogen:/autogen
      - /watorvapor/story.storage/repository.wator:/repository
    working_dir: "/opt/laravel"
    command: php artisan serve -vvv --host=127.0.0.1 --port=18081
  
  wator-laravel-ghost:
    build: laravel-wator
    network_mode: "host"
    volumes:
      - /watorvapor/app_www/wator:/opt/laravel
      - /watorvapor/rsaauth/wator:/opt/rsaauth
      - /watorvapor/wai.storage/conf:/nativeapi
      - /watorvapor/autogen:/autogen
      - /watorvapor/story.storage/repository.wator:/repository
    working_dir: "/opt/laravel"
    command: php artisan serve -vvv --host=127.0.0.1 --port=18082
    restart: always
   
  wator-laravel-clone:
    build: laravel-wator
    network_mode: "host"
    volumes:
      - /watorvapor/app_www/wator:/opt/laravel
      - /watorvapor/rsaauth/wator:/opt/rsaauth
      - /watorvapor/wai.storage/conf:/nativeapi
      - /watorvapor/autogen:/autogen
      - /watorvapor/story.storage/repository.wator:/repository
    working_dir: "/opt/laravel"
    command: php artisan serve -vvv --host=127.0.0.1 --port=18083
    restart: always

  wator-laravel-Schedule:
    build: laravel-wator
    network_mode: "host"
    volumes:
      - /watorvapor/app_www/wator:/opt/laravel
    working_dir: "/opt/laravel"
    command: ./startSchedule.sh
    restart: always

  wator-ws-notify:
    image: node:slim
    network_mode: "host"
    volumes:
      - /watorvapor/app_www/ws_service:/opt/wc
    working_dir: "/opt/wc"
    command: node ./notify.js
    restart: always
    
  redis:
    image: redis
    network_mode: "host"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis/data:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    restart: always
