version: '3'
services:
  wator-nginx:
    build: nginx-wator
    ports:
      - "18081:80"
    restart: always
  wator-laravel:
    build: laravel-wator
    ports:
      - "127.0.0.1:18080:8000"
    command: find /opt/laravel
    #command: cd /opt/laravel && php artisan serve
    volumes:
      - /watorvapor/app_www/wator:/opt/laravel
    restart: always
