version: '3'
services:
  wator-laravel:
    build: laravel-wator
    ports:
      - "127.0.0.1:18080:8000"
    volumes:
      - /watorvapor/app_www/wator:/opt/laravel
    working_dir: "/opt/laravel"
    command: php artisan serve -vvv --host=0.0.0.0
    restart: always
